import {
    Home,
    Briefcase,
    ShoppingCart,
    Settings,
    User,
    UserPen,
    CircleUser,
    Phone,
    Camera,
    Image,
    Music,
    Video,
    FileText,
    Layout,
    BarChart2,
    ClipboardList,
    LogIn,
    UserPlus,
    Package,
    Download,
    Bell,
    CreditCard,
    History,
    FormInput,
    Calendar,
    CalendarCheck,
    Ticket,
    Mail,
    MessageCircle,
    BookOpen,
    VideoIcon,
    Mic,
    Map,
    ConciergeBell,
    ChefHat
  } from "lucide-react";
  
  export const navItems = [
    {
      label: "Home",
      icon: Home,
      children: [
        { label: "Index", href: "/", icon: Layout },
        { label: "UI", href: "/ui", icon: Layout },
        { label: "Layouts", href: "/layouts", icon: Layout },
        { label: "Sliders", href: "/sliders", icon: Layout },
      ],
    },
    {
      label: "✔️ Portfolio",
      icon: Image,
      children: [
        { label: "Blog", href: "/blog", icon: FileText },
        { label: "Photography", href: "/photos", icon: Camera },
        { label: "Artwork", href: "/artwork", icon: Image },
        { label: "Music Player", href: "/amplitude", icon: Music },
        { label: "Video Player", href: "/videos", icon: Video },
        { label: "3D Art", href: "/3d", icon: Layout },
      ],
    },
    {
      label: "✔️ Admin",
      icon: Settings,
      children: [
        { label: "Dashboard", href: "/dashboard", icon: Layout },
        { label: "C.R.U.D.", href: "/crud", icon: ClipboardList },
        { label: "Login", href: "/login", icon: LogIn },
        { label: "Register", href: "/register", icon: UserPlus },
        { label: "Users", href: "/users", icon: User },
        { label: "Roles", href: "/rbac", icon: Settings },
        { label: "Statistics", href: "/statistics", icon: BarChart2 },
        { label: "Map", href: "/map", icon: Map },
        { label: "Typography", href: "/typography", icon: FileText },
        { label: "Settings", href: "/settings", icon: Settings },
      ],
    },
    {
      label: "✔️ eCommerce",
      icon: ShoppingCart,
      children: [
        { label: "Orders", href: "/orders", icon: ClipboardList },
        { label: "Products", href: "/products", icon: Package },
        { label: "Cart", href: "/cart", icon: ShoppingCart },
        { label: "Checkout", href: "/checkout", icon: CreditCard },
        { label: "Downloads", href: "/downloads", icon: Download },
        { label: "Subscriptions", href: "/subscriptions", icon: Bell },
      ],
    },
    {
      label: "Services",
      icon: Briefcase,
      children: [
        { label: "Schedule", href: "/schedule", icon: Calendar },
        { label: "Appointments", href: "/appointments", icon: CalendarCheck },
        { label: "Events", href: "/events", icon: Calendar },
        { label: "Tickets", href: "/tickets", icon: Ticket },
        { label: "Form Builder", href: "/form", icon: FormInput },
        { label: "Restaurant Menu", href: "/menu", icon: ClipboardList },
        { label: "Food Orders", href: "/food-orders", icon: ConciergeBell },
        { label: "All Food Orders", href: "/all-food-orders", icon: ChefHat },
      ],
    },
    {
      label: "✔️ Profile",
      icon: User,
      children: [
        { label: "View Profile", href: "/view-profile", icon: CircleUser },
           { label: "Edit Profile", href: "/edit-profile", icon: UserPen },
        { label: "Register", href: "/register", icon: UserPlus },
        { label: "Billing", href: "/billing", icon: CreditCard },
        { label: "History", href: "/history", icon: History },
      ],
    },
    {
      label: "Contact",
      icon: Phone,
      children: [
        { label: "Newsletter", href: "/newsletter", icon: Mail },
        { label: "Email", href: "/email", icon: Mail },
        { label: "Chat", href: "/chat", icon: MessageCircle },
        { label: "Stories", href: "/stories", icon: BookOpen },
        { label: "Forum", href: "/forum", icon: MessageCircle },
      ],
    },
  ];
  